bce:
  type: losses.BCEWithLogitsLoss

aufloss:
  type: losses.AsymmetricUnifiedFocalLoss

sufloss:
  type: losses.SymmetricUnifiedFocalLoss

base:
  type: losses.ComboLoss 

DiceLoss:
  type: losses.DiceLoss

BCEDiceLoss:
 type: losses.BCEDiceLoss