bce:
  type: losses.BCEWithLogitsLoss

aufloss:
  type: losses.AsymmetricUnifiedFocalLoss

sufloss:
  type: losses.SymmetricUnifiedFocalLoss

base:
  type: losses.ComboLoss 

dice_loss:
  type: losses.dice_loss

DiceLoss:
  type: losses.DiceLoss