bce:
  type: losses.BCEWithLogitsLoss

aufloss:
  type: losses.AsymmetricUnifiedFocalLoss

sufloss:
  type: losses.SymmetricUnifiedFocalLoss

base:
  type: losses.ComboLoss 

structure_loss: 
  type: losses.structure_loss
