pranet:
  model:
    type: models.PraNet
    name: PraNet
    channel: 32
    output_stride: 32
    pretrained: True

hardnet: 
  model:
    type: models.HarDMSEG
  
esfpnet: #still-todo
  model:
    type: models.ESFPNet
    model_type: B4
  max_supported_bs: 8

uacanet:
  model:
    type: models.UACANet
    name: UACANet
    channel: 256
    output_stride: 16
    pretrained: True

segformer:
  model:
    type: models.Segformer
    decode_head_params:
      decoder_hidden_size: 768
      hidden_sizes: &hidden_sizes [ 64, 128, 320, 512]
      num_classes: 1
      classifier_dropout_prob: 0.1
      reshape_last_stage: &reshape_last True
    backbone_params:
      attention_probs_dropout_prob: 0
      depths: [3 ,4, 18, 3]
      hidden_sizes: *hidden_sizes
      drop_path_rate: 0.1
      hidden_act: gelu
      hidden_dropout_prob: 0
      mlp_ratios: [ 4, 4, 4, 4 ]
      num_attention_heads: [ 1, 2, 5, 8 ]
      num_channels: 12
      patch_sizes: [ 7, 3, 3, 3 ]
      reshape_last_stage: *reshape_last
      sr_ratios: [8, 4, 2, 1]
      strides: [4, 2, 2, 2]
    weights:
      segformer: models/HFSegformer/weights/HF_mit_b3_12c.pth
    
unetpp:
  model:
    type: models.UnetPlusPlus
    encoder_name: resnet50
    classes: 1
    encoder_weights: imagenet

unet:
  model:
    type: models.Unet
    encoder_name: resnet50
    classes: 1
    encoder_weights: imagenet
