CE_Net:
  model:
    type: models.CE_Net_
    
pranet:
  model:
    type: models.PraNet
    name: PraNet
    channel: 32
    output_stride: 32
    pretrained: True

hardnet: 
  model:
    type: models.HarDMSEG

uacanet:
  model:
    type: models.UACANet
    name: UACANet
    channel: 256
    output_stride: 16
    pretrained: True
   
unetpp:
  model:
    type: models.UnetPlusPlus
    encoder_name: resnet50
    classes: 1
    encoder_weights: imagenet

unet:
  model:
    type: models.Unet
    encoder_name: resnet50
    classes: 1
    encoder_weights: imagenet
